config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#index'
  resources :books, only: :index do
    resources :orders, only: :create
  end
  resources :orders, only: :index
  resources :books
  delete 'order/:id', to: 'orders#destroy', as: 'destroy_order'
  delete 'orders/clean', to: 'orders#clean', as: 'clean_orders'

  resources :billings, only: [] do
    collection do
      get 'pre-pay'
      get 'execute'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
    belongs_to :user
    has_many :orders
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :orders
    has_many :users, through: :orders
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :book
    belongs_to :user
    belongs_to :billing, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :products, through: :orders
  has_many :billing
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
    def pre_pay
        orders = current_user.orders.where(paid: false)
        total = 0
        orders.each do |order|
            total += (order.book.price * order.quantity)
        end
        items = orders.map do |order|
            item = {}
            item[:title] = order.book.title 
            item[:sku] = order.book.id.to_s
            item[:price] = order.book.price
            item[:currency] = 'USD'
            item[:quantity] = order.quantity
            item  
        end
        payment = PayPal::SDK::REST::Payment.new({
            intent: 'sale',
            payer: {
                payment_method: 'Paypal'
            },
            redirect_urls: {
                return_url: "http://localhost:3000/billings/execute",
                cancel_url: "http://localhost:3000/" 
                #return_url: 'https://rocky-temple-55721.herokuapp.com/', 
                #cancel_url: 'https://rocky-temple-55721.herokuapp.com/'
            },
            
                transactions: [
                    {
                        item_list: {
                            items: items
                        },
                        amount: {
                            total: total.to_s, 
                            currency: 'USD'
                        },
                        description: 'Compra desde mi tienda ocso en Rails'
                    }
                ]
            
        })
        if payment.create 
            redirect_url = payment.links.find{|link| link.method == 'REDIRECT'}.href 
            redirect_to redirect_url 
        else  
            render json: payment.errors  
        end 
    end
    
    def execute
        paypal_payment = PayPal::SDK::REST::Payment.find(params[:paymentId])
        if paypal_payment.execute(payer_id: params[:PayerID])
            amount = paypal_payment.transactions.first.amount.total
            billing = Billing.create(
                user_id: current_user.id,
                code: paypal_payment.id,
                amount: amount,
                payment_method: 'PayPal',
                currency: 'USD'
            )
            orders = current_user.orders.where(paid: false)
            orders.update_all(paid: true, billing_id: billing.id)
            redirect_to root_path, notice: 'El pago se ha realizado exitosamente :D '
        else  
            redirect_to root_path, notice: 'No se ha podido realizar el pago con PayPal'

        end 
    end
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: [:show, :edit, :update, :destroy]
  
    # GET /books
    # GET /books.json
    def index
      @books = Book.all
    end
  
    # GET /books/1
    # GET /books/1.json
    def show
    end
  
    # GET /books/new
    def new
      @book = Book.new
    end
  
    # GET /books/1/edit
    def edit
    end
  
    # POST /books
    # POST /books.json
    def create
      @book = Book.new(book_params)
  
      respond_to do |format|
        if @book.save
          format.html { redirect_to @book, notice: 'Book was successfully created.' }
          format.json { render :show, status: :created, location: @book }
        else
          format.html { render :new }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /books/1
    # PATCH/PUT /books/1.json
    def update
      respond_to do |format|
        if @book.update(book_params)
          format.html { redirect_to @book, notice: 'Book was successfully updated.' }
          format.json { render :show, status: :ok, location: @book }
        else
          format.html { render :edit }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /books/1
    # DELETE /books/1.json
    def destroy
      @book.destroy
      respond_to do |format|
        format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_book
        @book = Book.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def book_params
        params.require(:book).permit(:title, :author, :price)
      end
  end
  

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!
    def index
      @orders = Order.where(user_id: current_user.id, paid: false)
    end
    def create
      book = Book.find(params[:book_id])
      order = Order.find_or_create_by(user_id: current_user.id, book_id: book.id, paid: false)
      order.quantity += 1
      if order.save 
        redirect_to root_path, notice: 'Se ha reservado el libro'
      else 
        redirect_to root_path, alert: 'No se ha podido reservar el libro'
    end  
    end
    def destroy
      order = Order.find(params[:id])
      order.destroy 
      redirect_to orders_path, notice: 'Se ha quitado el libro de las reservas'
    end
    def clean
      order = Order.where(paid: false)
      order.destroy_all
      redirect_to orders_path, notice: 'Ya no tienes ningún libro reservado'
    end
    
  end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libros</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= number_to_currency(book.price, unit: 'CLP$') %></td>
        <td><%= link_to 'Reservar', book_orders_path(book.id), method: :post %> </td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortalLibros</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Reservas</h1>

<% if @orders.length < 1 %>
    <h3>No hay Reservas</h3>
<% else %>
    <table>
        <thead>
            <th>Nombre</th>
            <th>Autor</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th>Total</th>
        </thead>
        <tbody>
            <% total = 0%>
            <% @orders.each do |order|%>
                <% total += (order.book.price * order.quantity)%>
                <tr>
                    <td><%= order.book.title %> </td>
                    <td><%= order.book.author%></td>
                    <td><%= number_to_currency(order.book.price, unit: "CLP$")%> </td>
                    <td>|  <%= order.quantity %> |</td>
                    <td><%= number_to_currency((order.book.price*order.quantity), unit: 'CLP$') %> </td>
                    <td><%= link_to 'Quitar', destroy_order_path(order.id), method: :delete%> </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <p>Total: <%= number_to_currency(total, unit: "CLP$")%> </p> 
    <p><%= link_to 'Eliminar reservas', clean_orders_path, method: :delete %> </p>
    <p><%= link_to 'Pagar', pre_pay_billings_path %> </p>
<%end%>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>